version: '3'
services:
    openldap:
        container_name: openldap
        image: mwaeckerlin/openldap
        volumes:
            - /srv/docker/slapd/database:/var/lib/ldap
            - /srv/docker/slapd/etc:/etc/ldap
            #- ./slapd/certs:/ssl/certs
        ports:
            - 636:636
            - 389:389
        environment:
            - DOMAIN=luochunhui.com
            - ORGANIZATION="Luo Chunhui"
            - PASSWORD=admin
        networks:
          - user

networks:
  user:
    driver: bridge

#docker cp ca-certfile.crt openldap:/ssl/certs/marc.waeckerlin.org-ca.crt
#docker cp certfile.pem openldap:/ssl/certs/marc.waeckerlin.org.pem
#docker cp certfile.key openldap:/ssl/certs/marc.waeckerlin.org.key

