apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
    app: openldap
  name: openldap
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openldap
        app: openldap
    spec:
      containers:
      - name: openldap
        image: mwaeckerlin/openldap
        env:
          - name: DOMAIN
            value: gkewang.cn
          - name: HOSTNAME
            value: ldap.gkewang.cn
          - name: ORGANIZATION
            value: 'dev gkewang'
          - name: PASSWORD
            value: 'mmMr3Z9sUg$R'
        ports:
          - containerPort: 636
          - containerPort: 389
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/ldap
            name: openldap-claim0
          - mountPath: /etc/ldap
            name: openldap-claim1
      restartPolicy: Always
      volumes:
        - name: openldap-claim0
          persistentVolumeClaim:
            claimName: openldap-lib-pvc
        - name: openldap-claim1
          persistentVolumeClaim:
            claimName: openldap-etc-pvc
status: {}
